#!/usr/bin/env python3
"""Generates src/core/bidi_tables.zig from the Unicode Character Database.

Usage: python3 tools/gen-bidi-tables.py <dir> > src/core/bidi_tables.zig
where <dir> contains DerivedBidiClass.txt (from ucd/extracted/) and
BidiBrackets.txt, both from the same UCD version.

The output is checked in; regenerate only on a deliberate Unicode
upgrade — bidi classes feed layout, so a table change can move pixels.
"""
import re
import sys

CLASSES = [
    "L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S",
    "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI",
]

# @missing lines spell classes out long-form; assigned lines use codes.
LONG_NAMES = {
    "Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL",
    "European_Number": "EN", "European_Separator": "ES",
    "European_Terminator": "ET", "Arabic_Number": "AN",
    "Common_Separator": "CS", "Nonspacing_Mark": "NSM",
    "Boundary_Neutral": "BN", "Paragraph_Separator": "B",
    "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON",
    "Left_To_Right_Embedding": "LRE", "Left_To_Right_Override": "LRO",
    "Right_To_Left_Embedding": "RLE", "Right_To_Left_Override": "RLO",
    "Pop_Directional_Format": "PDF", "Left_To_Right_Isolate": "LRI",
    "Right_To_Left_Isolate": "RLI", "First_Strong_Isolate": "FSI",
    "Pop_Directional_Isolate": "PDI",
}


def norm(cls):
    cls = LONG_NAMES.get(cls, cls)
    assert cls in CLASSES, cls
    return cls

MAX_CP = 0x110000


def parse_ranges(path):
    """Returns (missing, assigned): lists of (start, end, class)."""
    missing, assigned = [], []
    line_re = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)")
    miss_re = re.compile(
        r"^# @missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)")
    with open(path) as f:
        for line in f:
            m = miss_re.match(line)
            if m:
                missing.append((int(m.group(1), 16), int(m.group(2), 16),
                                norm(m.group(3))))
                continue
            if line.startswith("#") or not line.strip():
                continue
            m = line_re.match(line)
            if m:
                start = int(m.group(1), 16)
                end = int(m.group(2), 16) if m.group(2) else start
                assigned.append((start, end, norm(m.group(3))))
    return missing, assigned


def build_class_map(missing, assigned):
    classes = ["L"] * MAX_CP
    # @missing lines appear in file order; later ones override (the first
    # is the global default, the rest carve out R/AL/ET blocks).
    for start, end, cls in missing:
        for cp in range(start, min(end + 1, MAX_CP)):
            classes[cp] = cls
    for start, end, cls in assigned:
        for cp in range(start, min(end + 1, MAX_CP)):
            classes[cp] = cls
    return classes


def compress(classes):
    ranges = []
    start = 0
    for cp in range(1, MAX_CP + 1):
        if cp == MAX_CP or classes[cp] != classes[start]:
            ranges.append((start, cp - 1, classes[start]))
            start = cp
    return ranges


def parse_brackets(path):
    pairs = []
    line_re = re.compile(
        r"^([0-9A-F]+)\s*;\s*([0-9A-F]+)\s*;\s*([oc])")
    with open(path) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            m = line_re.match(line)
            if m:
                pairs.append((int(m.group(1), 16), int(m.group(2), 16),
                              m.group(3)))
    return sorted(pairs)


def main():
    ucd = sys.argv[1]
    missing, assigned = parse_ranges(f"{ucd}/DerivedBidiClass.txt")
    ranges = compress(build_class_map(missing, assigned))
    # Dropping trailing default-L ranges: the lookup's miss path returns .L.
    non_l = [r for r in ranges if r[2] != "L"]
    brackets = parse_brackets(f"{ucd}/BidiBrackets.txt")

    version = "unknown"
    with open(f"{ucd}/DerivedBidiClass.txt") as f:
        m = re.search(r"DerivedBidiClass-([\d.]+)\.txt", f.readline())
        if m:
            version = m.group(1)

    print(f"""//! Generated by tools/gen-bidi-tables.py from UCD {version} —
//! do not edit. DerivedBidiClass.txt (defaults materialized from its
//! @missing lines, then compressed; L ranges are omitted because the
//! lookup's miss path is .L) and BidiBrackets.txt.

/// UAX #9 bidi character classes, in the order the tables encode.
pub const Class = enum(u8) {{
    {", ".join(c for c in CLASSES)},
}};
""")
    print(f"pub const class_ranges = [{len(non_l)}]ClassRange{{")
    for start, end, cls in non_l:
        print(f"    .{{ .start = 0x{start:X}, .end = 0x{end:X}, "
              f".class = .{cls} }},")
    print("};")
    print("""
pub const ClassRange = struct { start: u32, end: u32, class: Class };
""")
    print(f"pub const bracket_pairs = [{len(brackets)}]BracketPair{{")
    for cp, pair, kind in brackets:
        print(f"    .{{ .cp = 0x{cp:X}, .pair = 0x{pair:X}, "
              f".open = {'true' if kind == 'o' else 'false'} }},")
    print("};")
    print("""
pub const BracketPair = struct { cp: u32, pair: u32, open: bool };
""")


if __name__ == "__main__":
    main()
