//! The public surface, as text a build can compare.
//!
//! `revision` is the one machine-checked statement of which nokre a
//! consumer was written against, and four pins across three repositories
//! rest on it. It is hand-bumped, and a hand-bumped constant is only as
//! good as the memory of whoever last changed the contract: revision 53
//! shipped `dom.Csp`, `dom.CspError`, `Document.csp` and
//! `LocaleStub.csp` and left the constant where it was. Nothing noticed.
//! It surfaced a revision later, when a consumer moved its own pin and
//! the build told it the truth.
//!
//! So the surface is written down. This walk renders every public
//! declaration reachable from the root module — namespaces, types, their
//! fields, enum and error members, function signatures, and the *values*
//! of scalar constants — into one deterministic document, and
//! `surface_test.zig` holds `public_surface.txt` to it.
//!
//! **The revision is inside the document, not beside it.** That is what
//! makes forgetting impossible rather than merely visible: the recorded
//! surface cannot be refreshed while the constant stands still, because
//! the constant is one of the lines being refreshed. A contract change
//! that skips the bump has nothing it is allowed to record.
//!
//! **What counts as the surface is everything a consumer can name.**
//! Zig has no `pub(crate)`, so a helper that is `pub` for a sibling
//! module is reachable at `nokre.layout.pageColumn` and is therefore
//! contract whether anyone meant it to be. Recording it costs a bump on
//! roughly one commit in ten that changes no consumer's behaviour; not
//! recording it costs the thing this exists to catch. The asymmetry
//! decides it — a bump nobody needed is an integer and a scheduled
//! adoption, a bump nobody made is a consumer compiling against a
//! library it did not expect. Over-bumping is the sanctioned direction.
//!
//! Enum members are in for a sharper reason than completeness: a `switch`
//! without an `else` is exhaustive, so adding one member breaks every
//! consumer that switches on that enum. `IconName`'s glyphs are contract
//! by the same rule as anything else here.
//!
//! **Two things the record is not.** It is read under `zig test`, on the
//! host that runs it, so a decl that forks on `builtin.is_test` or on the
//! OS is recorded in that flavour — `services.locale.Service` resolves to
//! `Mock` here, and both `Mock` and `PlatformService` are separately
//! public so both shapes are in the document anyway. And it is the shape
//! of the surface, never its meaning: a function whose signature stands
//! still while its behaviour moves is a contract change this cannot see,
//! and the bump for that one is still a judgement. Goldens are
//! host-specific for the same reason and say so.

const std = @import("std");
const nokre = @import("nokre.zig");

/// Deeper than anything this library nests today. A path that reaches it
/// is recorded by name with a `…` line rather than walked, so a library
/// that grows past the cap says so in the artifact instead of silently
/// dropping the tail.
const max_depth = 6;

pub fn write(gpa: std.mem.Allocator, out: *std.ArrayList(u8)) !void {
    @setEvalBranchQuota(6_000_000);
    try out.appendSlice(gpa,
        \\# nokre public surface — generated by src/surface.zig, never edited by hand.
        \\# `nokre.revision` is a line in this document on purpose: the record cannot
        \\# be refreshed without moving it. See src/surface.zig.
        \\
    );
    try walk(nokre, "nokre", 0, gpa, out);
}

fn walk(
    comptime T: type,
    comptime prefix: []const u8,
    comptime depth: usize,
    gpa: std.mem.Allocator,
    out: *std.ArrayList(u8),
) !void {
    const info = comptime @typeInfo(T);
    inline for (comptime declsOf(info)) |d| {
        const name = prefix ++ "." ++ d.name;
        const F = @TypeOf(@field(T, d.name));
        if (F == type) {
            const V = @field(T, d.name);
            try out.print(gpa, "{s} {s}\n", .{ name, kindOf(V) });
            if (depth + 1 > max_depth) {
                try out.print(gpa, "{s} …\n", .{name});
            } else {
                try walk(V, name, depth + 1, gpa, out);
            }
        } else if (comptime scalar(F)) {
            // The value, not just the type. `max_nav_items` moving from
            // 5 to 6 is a contract change with no shape to notice it by,
            // and one shipped unbumped.
            try out.print(gpa, "{s} : {s} = {any}\n", .{ name, @typeName(F), @field(T, d.name) });
        } else {
            try out.print(gpa, "{s} : {s}\n", .{ name, typeText(F) });
        }
    }
    switch (info) {
        .@"struct" => |s| inline for (s.fields) |f| {
            // Whether a field has a default is contract: a consumer's
            // struct literal compiles or does not by it.
            try out.print(gpa, "{s}#{s} : {s}{s}\n", .{
                prefix,
                f.name,
                typeText(f.type),
                if (f.default_value_ptr == null) "" else " = default",
            });
        },
        .@"enum" => |s| inline for (s.fields) |f| {
            try out.print(gpa, "{s}#{s} = {d}\n", .{ prefix, f.name, f.value });
        },
        .@"union" => |s| inline for (s.fields) |f| {
            try out.print(gpa, "{s}#{s} : {s}\n", .{ prefix, f.name, typeText(f.type) });
        },
        .error_set => |set| if (set) |errs| {
            inline for (errs) |e| try out.print(gpa, "{s}!{s}\n", .{ prefix, e.name });
        },
        else => {},
    }
}

fn declsOf(comptime info: std.builtin.Type) []const std.builtin.Type.Declaration {
    return switch (info) {
        .@"struct" => |s| s.decls,
        .@"enum" => |s| s.decls,
        .@"union" => |s| s.decls,
        .@"opaque" => |s| s.decls,
        else => &.{},
    };
}

/// Constants whose *value* a consumer can depend on. Deliberately narrow:
/// a slice or a struct value would drag formatting decisions into the
/// record, and the shapes above already carry those.
fn scalar(comptime F: type) bool {
    return switch (@typeInfo(F)) {
        .int, .comptime_int, .bool, .@"enum" => true,
        else => false,
    };
}

/// An inferred error set names the function it was inferred from, which
/// renders as a `@typeInfo(@typeInfo(@TypeOf(…)))` chain that says
/// nothing a reader or a diff can use. It collapses to one word: what
/// changed about such a function is its parameters and its payload, and
/// both are still here.
fn typeText(comptime F: type) []const u8 {
    const name = @typeName(F);
    comptime var out: []const u8 = "";
    comptime var rest: []const u8 = name;
    inline while (comptime std.mem.indexOf(u8, rest, "@typeInfo(")) |at| {
        const close = comptime std.mem.indexOfPos(u8, rest, at, ").error_union.error_set") orelse break;
        out = out ++ rest[0..at] ++ "inferred";
        rest = rest[close + ").error_union.error_set".len ..];
    }
    return out ++ rest;
}

fn kindOf(comptime T: type) []const u8 {
    return switch (@typeInfo(T)) {
        .@"struct" => "struct",
        .@"enum" => "enum",
        .@"union" => "union",
        .@"opaque" => "opaque",
        .@"fn" => "fn",
        .error_set => "error",
        .pointer, .optional, .array => "alias",
        else => "value",
    };
}
