// Wayland shell. Thin by charter: a wl_surface, a gray8→XRGB blit into
// wl_shm buffers, input forwarding, text-input-v3 for IME. No timers past
// the one keyboard-repeat timerfd the compositor makes us own, no
// animation — nokre repaints only when state changes, and the event loop
// blocks in poll() at rest for zero idle CPU.
//
// X11 is deliberately not here (docs/roadmap.md): Wayland is the modern
// default and one backend is the charter. The pieces that ride this file
// without being part of the dumb shell contract — clipboard out, the
// deep-link inbound hook, the worker/a11y UI-thread hop — answer to their
// own service headers, exactly as the Windows and macOS shells arrange.
// _GNU_SOURCE (implies _POSIX_C_SOURCE): memfd_create, MFD_CLOEXEC, and
// the eventfd/SOCK_CLOEXEC flags are glibc extensions behind it.
#define _GNU_SOURCE
#include <errno.h>
#include <stdatomic.h>
#include <fcntl.h>
#include <poll.h>
#include <pthread.h>
#include <signal.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/eventfd.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/timerfd.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>

// wayland-scanner output, generated by build.zig into the module's
// include dir from the system protocol XML (stable/xdg-shell and
// unstable/text-input/v3). Committing generated code is the anti-pattern
// the qrcodegen/harfbuzz vendoring avoids; here the toolchain regenerates.
#include "xdg-shell-client-protocol.h"
#include "text-input-unstable-v3-client-protocol.h"

#include "../shell.h"
#include "../../services/deep_link/deep_link.h"
#include "../../services/locale/locale.h"
#include "../../services/open_url/open_url.h"

// Optional appearance detection (xdg-desktop-portal over D-Bus). Isolated
// behind NOKRE_HAVE_DBUS so a build without libdbus still links — the shell
// then reports light, the honest default.
#ifdef NOKRE_HAVE_DBUS
#include <dbus/dbus.h>
#endif

#define NOKRE_SCROLL_PX_PER_NOTCH 48 // three body-text lines, the Windows/web policy

// One window by design; module state instead of per-window allocations,
// the Windows shell's shape.
static struct {
    nokre_shell_config config;

    struct wl_display *display;
    struct wl_registry *registry;
    struct wl_compositor *compositor;
    struct wl_shm *shm;
    struct xdg_wm_base *wm_base;
    struct wl_seat *seat;
    struct wl_pointer *pointer;
    struct wl_keyboard *keyboard;
    struct wl_data_device_manager *ddm;
    struct wl_data_device *data_device;
    struct zwp_text_input_manager_v3 *ti_manager;
    struct zwp_text_input_v3 *text_input;

    struct wl_surface *surface;
    struct xdg_surface *xdg_surface;
    struct xdg_toplevel *toplevel;

    int32_t logical_w, logical_h; // current surface size, logical px
    int32_t scale;                // integer buffer scale, >= 1
    int configured;               // first xdg_surface.configure seen
    int closed;                   // toplevel.close received
    // Content changed, awaiting a free buffer. Atomic because
    // nokre_shell_request_frame sets it from any thread while the UI
    // loop reads and clears it; every other field here is UI-thread
    // only.
    atomic_int dirty;

    // Double-buffered wl_shm: draw into whichever is free.
    struct {
        struct wl_buffer *buffer;
        uint8_t *data; // mmap'd, capacity `cap` bytes
        size_t cap;
        int32_t w, h; // buffer pixel size the mapping was made for
        int busy;     // held by the compositor until wl_buffer.release
    } bufs[2];

    // xkbcommon keyboard state.
    struct xkb_context *xkb_ctx;
    struct xkb_keymap *xkb_keymap;
    struct xkb_state *xkb_state;
    uint8_t mods; // NOKRE_MOD_* snapshot from the last modifiers event

    // Keyboard repeat: the compositor delegates it, so we drive one
    // timerfd for the currently-held repeatable key.
    int repeat_fd;
    int32_t repeat_rate;  // keys/sec, 0 disables
    int32_t repeat_delay; // ms before the first repeat
    uint32_t repeat_key;  // evdev keycode being repeated, 0 = none

    uint32_t seat_version; // bound wl_seat version (>= 8 gives value120)

    // Pointer: last surface-local position and the wheel remainder.
    int32_t ptr_x, ptr_y;
    int ptr_down; // a press is in flight, so motion is worth reporting
    int wheel_rem_x, wheel_rem_y; // value120 → px remainders
    int axis_rem_x, axis_rem_y;   // legacy wl_fixed axis → px remainders

    // Per-frame scroll accumulator (wl_pointer.frame batches axis events):
    // value120 wins when present, the legacy wl_fixed axis drives touchpad.
    int sf_have_v120, sf_have_axis;
    int sf_v120_x, sf_v120_y;
    wl_fixed_t sf_axis_x, sf_axis_y;

    // Integer output scales, tracked so wl_surface.enter can set g.scale.
    struct wl_output *out_objs[8];
    int32_t out_scales[8];
    int n_out;
    struct wl_output *surface_output; // the output the surface is on

    // The most recent input serial, for set_selection and IME commits.
    uint32_t last_serial;

    // text-input-v3 batch, applied on `done`.
    int ti_enabled;                 // enable sent, not yet disabled
    int ti_have_preedit;            // a preedit_string arrived this batch
    int ti_have_commit;             // a commit_string arrived this batch
    char ti_preedit[512];           // current composition
    int32_t ti_cursor;              // caret byte offset within ti_preedit
    char ti_commit[512];            // committed text this batch
    int ti_composing;               // a non-empty preedit is currently shown
    int ti_focused;                 // between text_input.enter and .leave
    uint32_t ti_serial;             // bump on every enable/commit, per protocol

    // Clipboard out: the current wl_data_source and the text it serves.
    struct wl_data_source *clip_source;
    char *clip_text;
    size_t clip_len;

    // Worker/a11y UI-thread hop: an eventfd the poll loop waits on, plus a
    // lock-protected queue of posted callbacks. nokre_shell_post_main and
    // nokre_shell_request_frame both write the eventfd from any thread.
    int wake_fd;
    pthread_mutex_t post_lock;
    struct nokre_post_item *post_head, *post_tail;

    // Deep-link single-instance: the primary owns this listening socket.
    int single_fd;
} g;

struct nokre_post_item {
    void (*work)(void *ctx);
    void *ctx;
    struct nokre_post_item *next;
};

// Forward decls for the service hooks defined at the bottom.
static void nokre_deep_link_dispatch(const char *utf8, size_t len);
static void report_appearance(void);

// ---- shm buffers ----

static int create_anon_fd(size_t size) {
    // memfd is Linux-native and needs no tmp path; libwayland is happy
    // with any fd that mmaps.
    int fd = memfd_create("nokre-shm", MFD_CLOEXEC);
    if (fd < 0) return -1;
    if (ftruncate(fd, (off_t)size) < 0) {
        close(fd);
        return -1;
    }
    return fd;
}

static void buffer_release(void *data, struct wl_buffer *wl_buffer) {
    (void)wl_buffer;
    int *busy = data;
    *busy = 0;
}
static const struct wl_buffer_listener buffer_listener = {.release = buffer_release};

// Ensures bufs[i] holds a wl_buffer sized w*h; returns 0 on failure.
static int ensure_buffer(int i, int32_t w, int32_t h) {
    if (g.bufs[i].buffer != NULL && g.bufs[i].w == w && g.bufs[i].h == h) return 1;
    if (g.bufs[i].buffer != NULL) {
        wl_buffer_destroy(g.bufs[i].buffer);
        munmap(g.bufs[i].data, g.bufs[i].cap);
        g.bufs[i].buffer = NULL;
    }
    size_t stride = (size_t)w * 4;
    size_t size = stride * (size_t)h;
    int fd = create_anon_fd(size);
    if (fd < 0) return 0;
    void *data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED) {
        close(fd);
        return 0;
    }
    struct wl_shm_pool *pool = wl_shm_create_pool(g.shm, fd, (int32_t)size);
    struct wl_buffer *buffer =
        wl_shm_pool_create_buffer(pool, 0, w, h, (int32_t)stride, WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);
    if (buffer == NULL) {
        munmap(data, size);
        return 0;
    }
    g.bufs[i].buffer = buffer;
    g.bufs[i].data = data;
    g.bufs[i].cap = size;
    g.bufs[i].w = w;
    g.bufs[i].h = h;
    g.bufs[i].busy = 0;
    wl_buffer_add_listener(buffer, &buffer_listener, &g.bufs[i].busy);
    return 1;
}

// Renders the current frame into a free buffer and commits it. Deferred
// (dirty stays set) when both buffers are still held by the compositor.
static void paint(void) {
    if (!g.configured || g.logical_w < 1 || g.logical_h < 1) return;
    int i = !g.bufs[0].busy ? 0 : (!g.bufs[1].busy ? 1 : -1);
    if (i < 0) {
        g.dirty = 1; // a release event will call back here
        return;
    }
    int32_t out_w = 0, out_h = 0;
    const uint8_t *pixels = g.config.on_frame(g.config.ctx, g.logical_w, g.logical_h, 0,
                                              g.scale, &out_w, &out_h);
    if (pixels == NULL || out_w <= 0 || out_h <= 0) return;
    if (!ensure_buffer(i, out_w, out_h)) return;

    // Expand gray8 to XRGB8888 (v | v<<8 | v<<16), one memcpy-shaped loop —
    // the Windows BGRX blit, byte-order-identical on little-endian.
    size_t count = (size_t)out_w * (size_t)out_h;
    uint32_t *dst = (uint32_t *)g.bufs[i].data;
    for (size_t p = 0; p < count; p++) {
        uint32_t v = pixels[p];
        dst[p] = v | (v << 8) | (v << 16);
    }

    g.bufs[i].busy = 1;
    g.dirty = 0;
    wl_surface_set_buffer_scale(g.surface, g.scale);
    wl_surface_attach(g.surface, g.bufs[i].buffer, 0, 0);
    // Damage everything (surface coords) — version-safe across wl_surface
    // v1+, unlike damage_buffer which is v4; the whole frame is fresh.
    wl_surface_damage(g.surface, 0, 0, INT32_MAX, INT32_MAX);
    wl_surface_commit(g.surface);
}

static void maybe_repaint(void) {
    if (g.config.wants_frame(g.config.ctx)) {
        g.dirty = 1;
        paint();
    }
}

// ---- xdg_surface / toplevel ----

static void xdg_surface_configure(void *data, struct xdg_surface *xdg_surface,
                                  uint32_t serial) {
    (void)data;
    xdg_surface_ack_configure(xdg_surface, serial);
    g.configured = 1;
    g.dirty = 1;
    paint(); // a configure must be answered with a fresh commit
}
static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

static void toplevel_configure(void *data, struct xdg_toplevel *toplevel,
                               int32_t width, int32_t height,
                               struct wl_array *states) {
    (void)data;
    (void)toplevel;
    (void)states;
    // 0×0 means "you choose" — keep the size we asked for at map time.
    if (width > 0) g.logical_w = width;
    if (height > 0) g.logical_h = height;
}
static void toplevel_close(void *data, struct xdg_toplevel *toplevel) {
    (void)data;
    (void)toplevel;
    g.closed = 1;
}
static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = toplevel_configure,
    .close = toplevel_close,
};

static void wm_base_ping(void *data, struct xdg_wm_base *wm_base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm_base, serial); // liveness check; keep the compositor happy
}
static const struct xdg_wm_base_listener wm_base_listener = {.ping = wm_base_ping};

// ---- surface scale (integer, from the outputs the surface is on) ----

static void surface_enter(void *data, struct wl_surface *surface,
                          struct wl_output *output);
static void surface_leave(void *data, struct wl_surface *surface,
                          struct wl_output *output) {
    (void)data;
    (void)surface;
    if (g.surface_output == output) g.surface_output = NULL;
}
static const struct wl_surface_listener surface_listener = {
    .enter = surface_enter,
    .leave = surface_leave,
};

// ---- pointer ----

static void pointer_enter(void *data, struct wl_pointer *pointer, uint32_t serial,
                          struct wl_surface *surface, wl_fixed_t sx, wl_fixed_t sy) {
    (void)data;
    (void)pointer;
    (void)surface;
    g.last_serial = serial;
    g.ptr_x = wl_fixed_to_int(sx);
    g.ptr_y = wl_fixed_to_int(sy);
}
static void pointer_leave(void *data, struct wl_pointer *pointer, uint32_t serial,
                          struct wl_surface *surface) {
    (void)data;
    (void)pointer;
    (void)serial;
    (void)surface;
}
static void pointer_motion(void *data, struct wl_pointer *pointer, uint32_t time,
                           wl_fixed_t sx, wl_fixed_t sy) {
    (void)data;
    (void)pointer;
    (void)time;
    g.ptr_x = wl_fixed_to_int(sx);
    g.ptr_y = wl_fixed_to_int(sy);
    // Only between a press and its release: a pointer merely crossing
    // the surface is not an event nokre has.
    if (g.ptr_down) {
        g.config.on_pointer(g.config.ctx, g.ptr_x, g.ptr_y, NOKRE_POINTER_MOVE);
        maybe_repaint();
    }
}
static void pointer_button(void *data, struct wl_pointer *pointer, uint32_t serial,
                           uint32_t time, uint32_t button, uint32_t state) {
    (void)data;
    (void)pointer;
    (void)time;
    g.last_serial = serial;
    // BTN_LEFT (linux/input-event-codes.h) is the press; core decides
    // what the matching release means.
    if (button != 0x110) return;
    int pressed = state == WL_POINTER_BUTTON_STATE_PRESSED;
    g.ptr_down = pressed;
    g.config.on_pointer(g.config.ctx, g.ptr_x, g.ptr_y,
                        pressed ? NOKRE_POINTER_DOWN : NOKRE_POINTER_UP);
    maybe_repaint();
}
// Scroll is batched per wl_pointer.frame and emitted once, so a v8
// compositor — which sends BOTH axis_value120 and the legacy axis for the
// same wheel notch — is never double-counted: value120 (the high-res wheel
// signal) wins when present, and the legacy axis only drives touchpad
// (finger) scrolling, which sends no value120. Below v5 there is no frame
// event, so the axis handler flushes immediately.
static int wheel_px(int *rem, int value120) {
    // 120 units per detent, like Windows WHEEL_DELTA; remainders accumulate
    // so precision wheels never drop motion.
    *rem += value120 * NOKRE_SCROLL_PX_PER_NOTCH;
    int px = *rem / 120;
    *rem -= px * 120;
    return px;
}
static int axis_px(int *rem, wl_fixed_t value) {
    // ~10 wl_fixed *whole* units per detent is libinput's convention,
    // and wl_fixed is 24.8 — so one notch is 10 * 256 raw units for
    // NOKRE_SCROLL_PX_PER_NOTCH px. Scale first and divide once at the
    // end, keeping the remainder: wl_fixed_to_int up front dropped every
    // slow (sub-unit) motion, and the integer 48/10 ran 4px/notch
    // instead of 4.8 — about 17% slow.
    *rem += (int)value * NOKRE_SCROLL_PX_PER_NOTCH;
    int px = *rem / (10 * 256);
    *rem -= px * (10 * 256);
    return px;
}
static void flush_scroll_frame(void) {
    int dx = 0, dy = 0;
    if (g.sf_have_v120) {
        dx = wheel_px(&g.wheel_rem_x, g.sf_v120_x);
        dy = wheel_px(&g.wheel_rem_y, g.sf_v120_y);
    } else if (g.sf_have_axis) {
        dx = axis_px(&g.axis_rem_x, g.sf_axis_x);
        dy = axis_px(&g.axis_rem_y, g.sf_axis_y);
    }
    g.sf_have_v120 = g.sf_have_axis = 0;
    g.sf_v120_x = g.sf_v120_y = 0;
    g.sf_axis_x = g.sf_axis_y = 0;
    if (dx == 0 && dy == 0) return;
    // Wayland's axes are already in core's convention: positive vertical is
    // downward content motion and positive horizontal is rightward — no
    // negation (unlike the Windows/macOS wheels, whose raw sign is
    // inverted). delta_x is horizontal, delta_y vertical (shell.h on_scroll).
    g.config.on_scroll(g.config.ctx, g.ptr_x, g.ptr_y, dx, dy, NOKRE_SCROLL_FREE);
    maybe_repaint();
}
static void pointer_axis(void *data, struct wl_pointer *pointer, uint32_t time,
                         uint32_t axis, wl_fixed_t value) {
    (void)data;
    (void)pointer;
    (void)time;
    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) g.sf_axis_y += value;
    else if (axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL) g.sf_axis_x += value;
    else return;
    g.sf_have_axis = 1;
    if (g.seat_version < 5) flush_scroll_frame(); // no frame event below v5
}
static void pointer_axis_value120(void *data, struct wl_pointer *pointer,
                                  uint32_t axis, int32_t value120) {
    (void)data;
    (void)pointer;
    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) g.sf_v120_y += value120;
    else if (axis == WL_POINTER_AXIS_HORIZONTAL_SCROLL) g.sf_v120_x += value120;
    else return;
    g.sf_have_v120 = 1; // value120 exists only on v5+, so frame always flushes
}
static void pointer_frame(void *data, struct wl_pointer *pointer) {
    (void)data;
    (void)pointer;
    flush_scroll_frame();
}
static void pointer_axis_source(void *d, struct wl_pointer *p, uint32_t s) {
    (void)d;
    (void)p;
    (void)s;
}
static void pointer_axis_stop(void *d, struct wl_pointer *p, uint32_t t, uint32_t a) {
    (void)d;
    (void)p;
    (void)t;
    (void)a;
}
static void pointer_axis_discrete(void *d, struct wl_pointer *p, uint32_t a, int32_t v) {
    (void)d;
    (void)p;
    (void)a;
    (void)v; // superseded by value120; ignored when both arrive
}
static const struct wl_pointer_listener pointer_listener = {
    .enter = pointer_enter,
    .leave = pointer_leave,
    .motion = pointer_motion,
    .button = pointer_button,
    .axis = pointer_axis,
    .frame = pointer_frame,
    .axis_source = pointer_axis_source,
    .axis_stop = pointer_axis_stop,
    .axis_discrete = pointer_axis_discrete,
    .axis_value120 = pointer_axis_value120,
};

// ---- keyboard (xkbcommon) ----

static int32_t key_from_sym(xkb_keysym_t sym) {
    switch (sym) {
        case XKB_KEY_Tab: case XKB_KEY_ISO_Left_Tab: return NOKRE_KEY_TAB;
        case XKB_KEY_Return: case XKB_KEY_KP_Enter: return NOKRE_KEY_ENTER;
        case XKB_KEY_space: return NOKRE_KEY_SPACE;
        case XKB_KEY_Escape: return NOKRE_KEY_ESCAPE;
        case XKB_KEY_BackSpace: return NOKRE_KEY_BACKSPACE;
        case XKB_KEY_Delete: case XKB_KEY_KP_Delete: return NOKRE_KEY_DELETE;
        case XKB_KEY_Left: case XKB_KEY_KP_Left: return NOKRE_KEY_LEFT;
        case XKB_KEY_Right: case XKB_KEY_KP_Right: return NOKRE_KEY_RIGHT;
        case XKB_KEY_Up: case XKB_KEY_KP_Up: return NOKRE_KEY_UP;
        case XKB_KEY_Down: case XKB_KEY_KP_Down: return NOKRE_KEY_DOWN;
        case XKB_KEY_Home: case XKB_KEY_KP_Home: return NOKRE_KEY_HOME;
        case XKB_KEY_End: case XKB_KEY_KP_End: return NOKRE_KEY_END;
        case XKB_KEY_Page_Up: case XKB_KEY_KP_Page_Up: return NOKRE_KEY_PAGE_UP;
        case XKB_KEY_Page_Down: case XKB_KEY_KP_Page_Down: return NOKRE_KEY_PAGE_DOWN;
        default: return 0;
    }
}

// Sends one key press through the contract: control keys as on_key,
// printable text as on_text, so nothing fires twice. IME composition owns
// everything while text-input is enabled and composing.
static void dispatch_key(uint32_t evdev_key) {
    xkb_keycode_t code = evdev_key + 8; // evdev → xkb keycode offset
    xkb_keysym_t sym = xkb_state_key_get_one_sym(g.xkb_state, code);
    int32_t key = key_from_sym(sym);
    // Space is both a control key and a character, so shell.h routes it
    // down one leg per press: the text path below while a field has
    // focus (xkbcommon hands it over as " " like any other character),
    // on_key everywhere else, where it is activation. There is no text
    // system here to defer the choice to, so it is made here.
    if (key == NOKRE_KEY_SPACE && g.config.wants_text_input(g.config.ctx)) key = 0;
    if (key != 0) {
        g.config.on_key(g.config.ctx, key, g.mods);
        maybe_repaint();
        return;
    }
    // Printable text — but never when Ctrl/Alt/Meta is down (those are
    // shortcuts, not text, matching the other shells' control-char filter).
    if (g.mods & (NOKRE_MOD_CTRL | NOKRE_MOD_ALT | NOKRE_MOD_META)) return;
    char utf8[64];
    int n = xkb_state_key_get_utf8(g.xkb_state, code, utf8, sizeof(utf8));
    // Drop control characters (they travel as keys) and empty output.
    if (n > 0 && (unsigned char)utf8[0] >= 0x20 && utf8[0] != 0x7F) {
        g.config.on_text(g.config.ctx, utf8, (size_t)n);
        maybe_repaint();
    }
}

static void arm_repeat(uint32_t evdev_key) {
    g.repeat_key = evdev_key;
    if (g.repeat_rate <= 0 || g.repeat_fd < 0) return;
    struct itimerspec its = {0};
    its.it_value.tv_sec = g.repeat_delay / 1000;
    its.it_value.tv_nsec = (long)(g.repeat_delay % 1000) * 1000000L;
    its.it_interval.tv_sec = 0;
    its.it_interval.tv_nsec = 1000000000L / g.repeat_rate;
    timerfd_settime(g.repeat_fd, 0, &its, NULL);
}
static void disarm_repeat(void) {
    g.repeat_key = 0;
    if (g.repeat_fd >= 0) {
        struct itimerspec off = {0};
        timerfd_settime(g.repeat_fd, 0, &off, NULL);
    }
}

static void kb_keymap(void *data, struct wl_keyboard *kb, uint32_t format, int fd,
                      uint32_t size) {
    (void)data;
    (void)kb;
    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) {
        close(fd);
        return;
    }
    char *map = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    if (map == MAP_FAILED) return;
    struct xkb_keymap *keymap = xkb_keymap_new_from_string(
        g.xkb_ctx, map, XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(map, size);
    if (keymap == NULL) return;
    struct xkb_state *state = xkb_state_new(keymap);
    if (state == NULL) {
        xkb_keymap_unref(keymap);
        return;
    }
    if (g.xkb_state) xkb_state_unref(g.xkb_state);
    if (g.xkb_keymap) xkb_keymap_unref(g.xkb_keymap);
    g.xkb_keymap = keymap;
    g.xkb_state = state;
}
static void kb_enter(void *data, struct wl_keyboard *kb, uint32_t serial,
                     struct wl_surface *surface, struct wl_array *keys) {
    (void)data;
    (void)kb;
    (void)surface;
    (void)keys;
    g.last_serial = serial;
    g.config.on_window_focus(g.config.ctx, 1);
}
static void kb_leave(void *data, struct wl_keyboard *kb, uint32_t serial,
                     struct wl_surface *surface) {
    (void)data;
    (void)kb;
    (void)serial;
    (void)surface;
    disarm_repeat();
    g.config.on_window_focus(g.config.ctx, 0);
}
static void kb_key(void *data, struct wl_keyboard *kb, uint32_t serial, uint32_t time,
                   uint32_t key, uint32_t state) {
    (void)data;
    (void)kb;
    (void)time;
    g.last_serial = serial;
    if (g.xkb_state == NULL) return;
    if (state == WL_KEYBOARD_KEY_STATE_PRESSED) {
        dispatch_key(key);
        // Only arm repeat for keys xkb marks repeatable (not modifiers).
        if (g.xkb_keymap &&
            xkb_keymap_key_repeats(g.xkb_keymap, key + 8))
            arm_repeat(key);
    } else if (key == g.repeat_key) {
        disarm_repeat();
    }
}
static void kb_modifiers(void *data, struct wl_keyboard *kb, uint32_t serial,
                         uint32_t mods_depressed, uint32_t mods_latched,
                         uint32_t mods_locked, uint32_t group) {
    (void)data;
    (void)kb;
    (void)serial;
    if (g.xkb_state == NULL) return;
    xkb_state_update_mask(g.xkb_state, mods_depressed, mods_latched, mods_locked, 0, 0,
                          group);
    uint8_t m = 0;
    if (xkb_state_mod_name_is_active(g.xkb_state, XKB_MOD_NAME_SHIFT,
                                     XKB_STATE_MODS_EFFECTIVE) > 0)
        m |= NOKRE_MOD_SHIFT;
    if (xkb_state_mod_name_is_active(g.xkb_state, XKB_MOD_NAME_CTRL,
                                     XKB_STATE_MODS_EFFECTIVE) > 0)
        m |= NOKRE_MOD_CTRL;
    if (xkb_state_mod_name_is_active(g.xkb_state, XKB_MOD_NAME_ALT,
                                     XKB_STATE_MODS_EFFECTIVE) > 0)
        m |= NOKRE_MOD_ALT;
    if (xkb_state_mod_name_is_active(g.xkb_state, XKB_MOD_NAME_LOGO,
                                     XKB_STATE_MODS_EFFECTIVE) > 0)
        m |= NOKRE_MOD_META;
    g.mods = m;
}
static void kb_repeat_info(void *data, struct wl_keyboard *kb, int32_t rate,
                           int32_t delay) {
    (void)data;
    (void)kb;
    g.repeat_rate = rate;
    g.repeat_delay = delay;
}
static const struct wl_keyboard_listener keyboard_listener = {
    .keymap = kb_keymap,
    .enter = kb_enter,
    .leave = kb_leave,
    .key = kb_key,
    .modifiers = kb_modifiers,
    .repeat_info = kb_repeat_info,
};

// ---- seat ----

static void seat_capabilities(void *data, struct wl_seat *seat, uint32_t caps) {
    (void)data;
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && g.pointer == NULL) {
        g.pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(g.pointer, &pointer_listener, NULL);
    }
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && g.keyboard == NULL) {
        g.keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(g.keyboard, &keyboard_listener, NULL);
    }
}
static void seat_name(void *data, struct wl_seat *seat, const char *name) {
    (void)data;
    (void)seat;
    (void)name;
}
static const struct wl_seat_listener seat_listener = {
    .capabilities = seat_capabilities,
    .name = seat_name,
};

// ---- text-input v3 (IME) ----

static void sync_text_input(void); // enable/disable per wants_text_input

static void ti_enter(void *data, struct zwp_text_input_v3 *ti,
                     struct wl_surface *surface) {
    (void)data;
    (void)ti;
    (void)surface;
    g.ti_focused = 1;
    sync_text_input();
}
static void ti_leave(void *data, struct zwp_text_input_v3 *ti,
                     struct wl_surface *surface) {
    (void)data;
    (void)surface;
    g.ti_focused = 0;
    if (g.ti_enabled) {
        zwp_text_input_v3_disable(ti);
        zwp_text_input_v3_commit(ti);
        g.ti_enabled = 0;
        g.ti_serial++;
    }
}
static void ti_preedit(void *data, struct zwp_text_input_v3 *ti, const char *text,
                       int32_t cursor_begin, int32_t cursor_end) {
    (void)data;
    (void)ti;
    (void)cursor_end;
    g.ti_have_preedit = 1;
    g.ti_preedit[0] = 0;
    g.ti_cursor = 0;
    if (text != NULL) {
        size_t n = strlen(text);
        if (n >= sizeof(g.ti_preedit)) n = sizeof(g.ti_preedit) - 1;
        memcpy(g.ti_preedit, text, n);
        g.ti_preedit[n] = 0;
        // cursor_begin is a byte offset into `text`; core renders the
        // caret there. -1 means "hide", which we clamp to the end.
        g.ti_cursor = (cursor_begin < 0 || (size_t)cursor_begin > n) ? (int32_t)n
                                                                     : cursor_begin;
    }
}
static void ti_commit_string(void *data, struct zwp_text_input_v3 *ti,
                             const char *text) {
    (void)data;
    (void)ti;
    g.ti_have_commit = 1;
    g.ti_commit[0] = 0;
    if (text != NULL) {
        size_t n = strlen(text);
        if (n >= sizeof(g.ti_commit)) n = sizeof(g.ti_commit) - 1;
        memcpy(g.ti_commit, text, n);
        g.ti_commit[n] = 0;
    }
}
static void ti_delete_surrounding(void *data, struct zwp_text_input_v3 *ti,
                                  uint32_t before, uint32_t after) {
    (void)data;
    (void)ti;
    (void)before;
    (void)after; // core owns no surrounding text to delete; nothing to do
}
static void ti_done(void *data, struct zwp_text_input_v3 *ti, uint32_t serial) {
    (void)data;
    (void)ti;
    (void)serial;
    // Apply the batch: a commit lands first, then the preedit is the live
    // composition. The three cases mirror the IMM32/InputConnection shells.
    if (g.ti_have_commit) {
        g.config.on_ime_commit(g.config.ctx, g.ti_commit, strlen(g.ti_commit));
        g.ti_composing = 0;
    }
    if (g.ti_have_preedit) {
        size_t n = strlen(g.ti_preedit);
        if (n > 0) {
            g.config.on_ime_update(g.config.ctx, g.ti_preedit, n, (size_t)g.ti_cursor);
            g.ti_composing = 1;
        } else if (g.ti_composing) {
            g.config.on_ime_cancel(g.config.ctx);
            g.ti_composing = 0;
        }
    }
    g.ti_have_commit = 0;
    g.ti_have_preedit = 0;
    maybe_repaint();
}
static const struct zwp_text_input_v3_listener text_input_listener = {
    .enter = ti_enter,
    .leave = ti_leave,
    .preedit_string = ti_preedit,
    .commit_string = ti_commit_string,
    .delete_surrounding_text = ti_delete_surrounding,
    .done = ti_done,
};

// Shows or hides the OS input path off wants_text_input, after each event —
// the iOS/web software-keyboard bargain: an on-screen keyboard (where the
// compositor offers one) follows the focused element's appetite for text.
static void sync_text_input(void) {
    // Only between enter and leave: the protocol forbids enable without
    // focus, and a disable is meaningless once the surface has lost it
    // (ti_leave already tore it down).
    if (g.text_input == NULL || !g.ti_focused) return;
    int want = g.config.wants_text_input(g.config.ctx) != 0;
    if (want && !g.ti_enabled) {
        zwp_text_input_v3_enable(g.text_input);
        // The document is only the composition (the other shells' rule):
        // no surrounding text, so the IME cannot be "smart".
        zwp_text_input_v3_set_content_type(
            g.text_input, ZWP_TEXT_INPUT_V3_CONTENT_HINT_NONE,
            ZWP_TEXT_INPUT_V3_CONTENT_PURPOSE_NORMAL);
        zwp_text_input_v3_commit(g.text_input);
        g.ti_enabled = 1;
        g.ti_serial++;
    } else if (!want && g.ti_enabled) {
        zwp_text_input_v3_disable(g.text_input);
        zwp_text_input_v3_commit(g.text_input);
        g.ti_enabled = 0;
        g.ti_serial++;
        if (g.ti_composing) {
            g.config.on_ime_cancel(g.config.ctx);
            g.ti_composing = 0;
        }
    }
}

// ---- clipboard out (wl_data_source) ----

static void ds_target(void *data, struct wl_data_source *src, const char *mime) {
    (void)data;
    (void)src;
    (void)mime;
}
static void ds_send(void *data, struct wl_data_source *src, const char *mime, int fd) {
    (void)data;
    (void)src;
    (void)mime;
    // A paste target asked for the selection; stream the bytes and close.
    const char *p = g.clip_text;
    size_t left = g.clip_len;
    while (left > 0) {
        ssize_t n = write(fd, p, left);
        if (n <= 0) break;
        p += n;
        left -= (size_t)n;
    }
    close(fd);
}
static void ds_cancelled(void *data, struct wl_data_source *src) {
    (void)data;
    // Another selection owner replaced us (or set_selection superseded
    // this source): drop it.
    if (src == g.clip_source) g.clip_source = NULL;
    wl_data_source_destroy(src);
}
static const struct wl_data_source_listener data_source_listener = {
    .target = ds_target,
    .send = ds_send,
    .cancelled = ds_cancelled,
};

// ---- data device (selection ownership needs the object; offers ignored) ----

static void dd_data_offer(void *d, struct wl_data_device *dd, struct wl_data_offer *o) {
    (void)d;
    (void)dd;
    (void)o; // nokre never reads the clipboard (clipboard.zig: write-only)
}
static void dd_selection(void *d, struct wl_data_device *dd, struct wl_data_offer *o) {
    (void)d;
    (void)dd;
    (void)o;
}
static void dd_enter(void *d, struct wl_data_device *dd, uint32_t s, struct wl_surface *w,
                     wl_fixed_t x, wl_fixed_t y, struct wl_data_offer *o) {
    (void)d; (void)dd; (void)s; (void)w; (void)x; (void)y; (void)o;
}
static void dd_leave(void *d, struct wl_data_device *dd) { (void)d; (void)dd; }
static void dd_motion(void *d, struct wl_data_device *dd, uint32_t t, wl_fixed_t x,
                      wl_fixed_t y) {
    (void)d; (void)dd; (void)t; (void)x; (void)y;
}
static void dd_drop(void *d, struct wl_data_device *dd) { (void)d; (void)dd; }
static const struct wl_data_device_listener data_device_listener = {
    .data_offer = dd_data_offer,
    .enter = dd_enter,
    .leave = dd_leave,
    .motion = dd_motion,
    .drop = dd_drop,
    .selection = dd_selection,
};

// ---- registry ----

// Defined below; registry_global binds each wl_output with this listener.
static const struct wl_output_listener output_listener;

static void registry_global(void *data, struct wl_registry *reg, uint32_t name,
                            const char *interface, uint32_t version) {
    (void)data;
    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        // v6 gives preferred_buffer_scale; bind low and read scale off
        // outputs instead, which every compositor supports.
        g.compositor = wl_registry_bind(reg, name, &wl_compositor_interface,
                                        version < 4 ? version : 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        g.shm = wl_registry_bind(reg, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        g.wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface, 1);
        xdg_wm_base_add_listener(g.wm_base, &wm_base_listener, NULL);
    } else if (strcmp(interface, wl_seat_interface.name) == 0) {
        // v8 gives axis_value120 (Windows-parity scrolling); v5 gives the
        // pointer.frame event scroll batching relies on.
        g.seat_version = version < 8 ? version : 8;
        g.seat = wl_registry_bind(reg, name, &wl_seat_interface, g.seat_version);
        wl_seat_add_listener(g.seat, &seat_listener, NULL);
    } else if (strcmp(interface, wl_output_interface.name) == 0) {
        // Bind each output (v2+ for the scale event) and track its integer
        // scale by index; wl_surface.enter then references one of these
        // objects, so it must be bound here for enter to fire at all.
        if (g.n_out < (int)(sizeof(g.out_objs) / sizeof(g.out_objs[0]))) {
            struct wl_output *o =
                wl_registry_bind(reg, name, &wl_output_interface, version < 2 ? version : 2);
            g.out_objs[g.n_out] = o;
            g.out_scales[g.n_out] = 1;
            wl_output_add_listener(o, &output_listener, (void *)(intptr_t)g.n_out);
            g.n_out++;
        }
    } else if (strcmp(interface, wl_data_device_manager_interface.name) == 0) {
        g.ddm = wl_registry_bind(reg, name, &wl_data_device_manager_interface,
                                 version < 3 ? version : 3);
    } else if (strcmp(interface, zwp_text_input_manager_v3_interface.name) == 0) {
        g.ti_manager =
            wl_registry_bind(reg, name, &zwp_text_input_manager_v3_interface, 1);
    }
}
static void registry_global_remove(void *data, struct wl_registry *reg, uint32_t name) {
    (void)data;
    (void)reg;
    (void)name;
}
static const struct wl_registry_listener registry_listener = {
    .global = registry_global,
    .global_remove = registry_global_remove,
};

// wl_output carries the integer scale; the surface reads it on enter.
static void output_geometry(void *d, struct wl_output *o, int32_t x, int32_t y,
                            int32_t pw, int32_t ph, int32_t sub, const char *make,
                            const char *model, int32_t transform) {
    (void)d; (void)o; (void)x; (void)y; (void)pw; (void)ph; (void)sub; (void)make;
    (void)model; (void)transform;
}
static void output_mode(void *d, struct wl_output *o, uint32_t f, int32_t w, int32_t h,
                        int32_t refresh) {
    (void)d; (void)o; (void)f; (void)w; (void)h; (void)refresh;
}
static void output_done(void *d, struct wl_output *o) { (void)d; (void)o; }
static void output_scale(void *data, struct wl_output *o, int32_t factor) {
    (void)o;
    int idx = (int)(intptr_t)data;
    int32_t s = factor < 1 ? 1 : factor;
    if (idx >= 0 && idx < g.n_out) g.out_scales[idx] = s;
    // If it is the output the surface is on, repaint at the new buffer scale.
    if (idx >= 0 && idx < g.n_out && g.out_objs[idx] == g.surface_output && s != g.scale) {
        g.scale = s;
        g.dirty = 1;
    }
}
static const struct wl_output_listener output_listener = {
    .geometry = output_geometry,
    .mode = output_mode,
    .done = output_done,
    .scale = output_scale,
};

static void surface_enter(void *data, struct wl_surface *surface,
                          struct wl_output *output) {
    (void)data;
    (void)surface;
    // The surface is now on this output; adopt its (already-bound) scale.
    g.surface_output = output;
    for (int i = 0; i < g.n_out; i++) {
        if (g.out_objs[i] == output) {
            if (g.out_scales[i] != g.scale) {
                g.scale = g.out_scales[i];
                g.dirty = 1;
            }
            break;
        }
    }
}

// ---- the on-demand event loop ----

static void drain_posts(void) {
    for (;;) {
        pthread_mutex_lock(&g.post_lock);
        struct nokre_post_item *item = g.post_head;
        if (item != NULL) {
            g.post_head = item->next;
            if (g.post_head == NULL) g.post_tail = NULL;
        }
        pthread_mutex_unlock(&g.post_lock);
        if (item == NULL) break;
        item->work(item->ctx);
        free(item);
    }
}

// ---- shell.h free functions ----

void nokre_shell_request_frame(void *view) {
    (void)view;
    g.dirty = 1;
    uint64_t one = 1;
    if (g.wake_fd >= 0) (void)!write(g.wake_fd, &one, sizeof(one));
}

void nokre_shell_post_main(void *view, void (*work)(void *ctx), void *ctx) {
    (void)view;
    struct nokre_post_item *item = malloc(sizeof(*item));
    if (item == NULL) return;
    item->work = work;
    item->ctx = ctx;
    item->next = NULL;
    pthread_mutex_lock(&g.post_lock);
    if (g.post_tail != NULL) g.post_tail->next = item;
    else g.post_head = item;
    g.post_tail = item;
    pthread_mutex_unlock(&g.post_lock);
    uint64_t one = 1;
    if (g.wake_fd >= 0) (void)!write(g.wake_fd, &one, sizeof(one));
}

void nokre_shell_write_clipboard(const char *utf8, size_t len) {
    if (g.ddm == NULL || g.data_device == NULL) return;
    char *copy = malloc(len ? len : 1);
    if (copy == NULL) return;
    memcpy(copy, utf8, len);
    free(g.clip_text);
    g.clip_text = copy;
    g.clip_len = len;
    // A fresh source per copy: offer the text mime-types a paste expects.
    struct wl_data_source *src = wl_data_device_manager_create_data_source(g.ddm);
    if (src == NULL) return;
    wl_data_source_add_listener(src, &data_source_listener, NULL);
    wl_data_source_offer(src, "text/plain;charset=utf-8");
    wl_data_source_offer(src, "text/plain");
    wl_data_source_offer(src, "UTF8_STRING");
    g.clip_source = src;
    wl_data_device_set_selection(g.data_device, src, g.last_serial);
    wl_display_flush(g.display);
}

// xdg-open rather than a portal call, for the reason oauth's desktop
// leg states (src/services/oauth/linux.c): opening a URI is the one
// desktop integration every environment has agreed on for two decades,
// and the portal's OpenURI would add a D-Bus round trip to reach the
// same handler. The shell itself never spawns processes, so the
// double-fork is borrowed from that leg too: the intermediate exits at
// once and is waited for here, xdg-open is re-parented to init, and
// the app never acquires a child it must reap — a GUI app has no event
// loop slot for SIGCHLD, and installing a handler would be a shell
// reaching into process-wide state.
void nokre_open_url_open(const char *url, size_t len) {
    if (len == 0) return;
    char *arg = malloc(len + 1);
    if (arg == NULL) return;
    memcpy(arg, url, len);
    arg[len] = '\0';
    pid_t middle = fork();
    if (middle < 0) {
        free(arg);
        return;
    }
    if (middle == 0) {
        pid_t grandchild = fork();
        if (grandchild == 0) {
            execlp("xdg-open", "xdg-open", arg, (char *)NULL);
            _exit(127); // xdg-open is not installed
        }
        _exit(grandchild < 0 ? 1 : 0);
    }
    int status = 0;
    while (waitpid(middle, &status, 0) < 0 && errno == EINTR) {
    }
    free(arg);
}

// ---- deep_link: single-instance forwarding over a Unix socket ----
// (docs/services.md; src/services/deep_link/deep_link.h). No packaging
// derivation, like the Windows leg: an unpackaged app has no verified
// https association, so the URL arrives through a custom scheme the
// developer registers in a .desktop `x-scheme-handler`. The OS launches a
// fresh process with the URL in argv; if this app already runs, the new
// process forwards the URL to it over an abstract Unix socket named for
// the app and exits — the Windows WM_COPYDATA / Android onNewIntent
// bargain — rather than stacking a duplicate window.

static void *g_deep_link_ctx = NULL;
static nokre_deep_link_cb g_deep_link_cb = NULL;
static char *g_deep_link_pending = NULL;
static size_t g_deep_link_pending_len = 0;

static void nokre_deep_link_dispatch(const char *utf8, size_t len) {
    if (g_deep_link_cb == NULL) {
        free(g_deep_link_pending);
        g_deep_link_pending = malloc(len ? len : 1); // malloc(1) marks "buffered"
        if (g_deep_link_pending == NULL) {
            g_deep_link_pending_len = 0;
            return;
        }
        memcpy(g_deep_link_pending, utf8, len);
        g_deep_link_pending_len = len;
        return;
    }
    g_deep_link_cb(g_deep_link_ctx, utf8, len);
    g.dirty = 1;
    maybe_repaint(); // the handler routed like any action; paint the result
}

void nokre_deep_link_install(void *ctx, nokre_deep_link_cb cb) {
    g_deep_link_ctx = ctx;
    g_deep_link_cb = cb;
    if (g_deep_link_pending != NULL) {
        char *url = g_deep_link_pending;
        size_t len = g_deep_link_pending_len;
        g_deep_link_pending = NULL;
        g_deep_link_pending_len = 0;
        cb(ctx, url, len);
        free(url);
    }
}

void nokre_deep_link_uninstall(void) {
    // Back to the pre-install posture: a forwarded URL that arrives now
    // is buffered for the next install, never delivered into per-app
    // state the app has already freed.
    g_deep_link_ctx = NULL;
    g_deep_link_cb = NULL;
}

// ---- locale service inbound hook ----
// (src/services/locale/locale.h). POSIX keeps the locale in the
// environment, in the precedence setlocale() itself obeys: LC_ALL
// overrides, else LC_MESSAGES — the message-catalog category, the one
// that decides which language a user reads, as opposed to LC_NUMERIC and
// friends — else LANG. We never call setlocale(): nokre's core is
// locale-independent by charter (integer math, no strtod, no strcoll),
// and mutating the C library's global locale just to read a string back
// out would be a side effect on the host program, not a read.
//
// This platform has NO change notification, and saying so is the honest
// answer rather than the lazy one: the environment is fixed at exec() and
// cannot change under a running process, Wayland has no locale event, and
// the one bus this shell already speaks — xdg-desktop-portal's Settings
// namespace — carries org.freedesktop.appearance keys and nothing about
// language. Sniffing a desktop-specific GSettings key would add a
// dependency to learn a value the process still could not adopt. So the
// callback fires exactly once, inside install, in the same register as
// the clipboard's absent read leg (ds_send's comment): a Linux user who
// switches language restarts the app, which is what every GTK and Qt
// program beside us requires too.
static void *g_locale_ctx = NULL;
static nokre_locale_cb g_locale_cb = NULL;

// Writes the BCP 47 tag into `out`, returning its length (0 = unknown).
static size_t locale_tag_from_env(char *out, size_t cap) {
    const char *v = getenv("LC_ALL");
    if (v == NULL || *v == 0) v = getenv("LC_MESSAGES");
    if (v == NULL || *v == 0) v = getenv("LANG");
    if (v == NULL || *v == 0) return 0;
    // "fa_IR.UTF-8@calendar=persian" -> "fa-IR". The codeset and modifier
    // are POSIX bookkeeping with no BCP 47 meaning, and the strip is
    // load-bearing, not cosmetic: l10n's rtTagEql compares lengths first,
    // so an unstripped value misses the exact-tag match and silently
    // demotes fa_IR to whatever bare fa bundle exists. '_' -> '-' because
    // the header promises a tag, and a shell that hands over a POSIX
    // locale name is trading on the matcher's tolerance for separators.
    size_t n = 0;
    while (v[n] != 0 && v[n] != '.' && v[n] != '@') n++;
    // "C" and "POSIX" name the absence of a locale, not a language. The
    // empty tag is the contract's "unknown"; Zig turns it into the app's
    // own template language. Guessing "en" here is not the shell's call.
    if (n == 1 && v[0] == 'C') return 0;
    if (n == 5 && memcmp(v, "POSIX", 5) == 0) return 0;
    if (n > cap) return 0; // empty beats a partial tag that resolves wrong
    for (size_t i = 0; i < n; i++) out[i] = (v[i] == '_') ? '-' : v[i];
    return n;
}

void nokre_locale_install(void *ctx, nokre_locale_cb cb) {
    g_locale_ctx = ctx;
    g_locale_cb = cb;
    // Read on demand and hand the bytes over borrowed: unlike the launch
    // URL above there is nothing to miss and so nothing to buffer — the
    // value is always readable, and Zig owns the cache.
    char buf[128]; // far past any real tag; longer, and we report unknown
    size_t len = locale_tag_from_env(buf, sizeof(buf));
    // Synchronous by contract: the boot read has to be warm before the
    // first build runs. No repaint follows — install lands inside
    // App.init, before nokre_shell_run owns a surface to invalidate.
    g_locale_cb(g_locale_ctx, buf, len);
}

void nokre_locale_uninstall(void) {
    // Nothing fires after install on this platform (no change
    // notification exists — see above), but the stored ctx is per-app
    // state the app is about to free, so it is forgotten all the same.
    g_locale_ctx = NULL;
    g_locale_cb = NULL;
}

// Abstract-namespace socket address for this app's title (leading NUL);
// abstract sockets need no filesystem path and vanish with the process.
static socklen_t single_addr(struct sockaddr_un *addr, const char *title) {
    memset(addr, 0, sizeof(*addr));
    addr->sun_family = AF_UNIX;
    // "\0nokre.<title>" — truncated to fit sun_path.
    const char *prefix = "nokre.";
    size_t cap = sizeof(addr->sun_path);
    addr->sun_path[0] = 0;
    size_t off = 1;
    for (const char *p = prefix; *p && off < cap; p++) addr->sun_path[off++] = *p;
    for (const char *p = title; *p && off < cap; p++) addr->sun_path[off++] = *p;
    return (socklen_t)(offsetof(struct sockaddr_un, sun_path) + off);
}

// Binds the single-instance socket. Returns the listening fd (we are the
// primary), or -1 after forwarding `launch` to the existing instance (the
// caller then exits) or on any error (we run standalone).
static int single_instance_bind(const char *title, const char *launch, size_t launch_len,
                                int *forwarded) {
    *forwarded = 0;
    struct sockaddr_un addr;
    socklen_t len = single_addr(&addr, title);
    int fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (fd < 0) return -1;
    if (bind(fd, (struct sockaddr *)&addr, len) == 0) {
        listen(fd, 8);
        return fd; // primary
    }
    // Address in use: an instance is running. Forward the URL and bow out.
    if (errno == EADDRINUSE && launch != NULL) {
        int c = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
        if (c >= 0 && connect(c, (struct sockaddr *)&addr, len) == 0) {
            size_t off = 0;
            while (off < launch_len) {
                ssize_t w = write(c, launch + off, launch_len - off);
                if (w <= 0) break;
                off += (size_t)w;
            }
            *forwarded = 1;
        }
        if (c >= 0) close(c);
    }
    close(fd);
    return -1;
}

// A forwarded URL arrived on the listening socket; read it and dispatch.
static void single_instance_accept(void) {
    // Non-blocking end to end: this runs on the UI loop, and any process
    // can connect to the socket — a client that connects and never
    // writes must not freeze the window in a blocking read. accept4
    // stamps the flag race-free; the loop takes what has arrived and
    // gives a stalled peer one short POLLIN wait, bounded, because the
    // real forwarder writes the whole URL and closes immediately.
    int c = accept4(g.single_fd, NULL, NULL, SOCK_NONBLOCK | SOCK_CLOEXEC);
    if (c < 0) return;
    char buf[4096];
    size_t off = 0;
    int waited = 0;
    for (;;) {
        ssize_t n = read(c, buf + off, sizeof(buf) - off);
        if (n > 0) {
            off += (size_t)n;
            if (off >= sizeof(buf)) break;
            continue;
        }
        if (n == 0) break; // EOF: the forwarder wrote and closed
        if ((errno == EAGAIN || errno == EWOULDBLOCK) && !waited) {
            waited = 1;
            struct pollfd pfd = {.fd = c, .events = POLLIN};
            if (poll(&pfd, 1, 100) > 0) continue;
        }
        break; // error, or a peer that stalls: drop it, keep the UI live
    }
    close(c);
    if (off > 0) nokre_deep_link_dispatch(buf, off);
}

// ---- appearance (xdg-desktop-portal Settings over D-Bus, optional) ----

#ifdef NOKRE_HAVE_DBUS
static DBusConnection *g_dbus;

// Reads org.freedesktop.appearance color-scheme: 1 = prefer dark.
static int portal_prefers_dark(void) {
    if (g_dbus == NULL) return 0;
    DBusMessage *msg = dbus_message_new_method_call(
        "org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop",
        "org.freedesktop.portal.Settings", "ReadOne");
    if (msg == NULL) return 0;
    const char *ns = "org.freedesktop.appearance", *key = "color-scheme";
    dbus_message_append_args(msg, DBUS_TYPE_STRING, &ns, DBUS_TYPE_STRING, &key,
                             DBUS_TYPE_INVALID);
    DBusError err;
    dbus_error_init(&err);
    DBusMessage *reply =
        dbus_connection_send_with_reply_and_block(g_dbus, msg, 1000, &err);
    dbus_message_unref(msg);
    if (reply == NULL) {
        dbus_error_free(&err);
        return 0; // no portal: light is the honest default
    }
    // Reply is v -> u (a variant wrapping a uint32).
    int dark = 0;
    DBusMessageIter it, variant;
    if (dbus_message_iter_init(reply, &it) &&
        dbus_message_iter_get_arg_type(&it) == DBUS_TYPE_VARIANT) {
        dbus_message_iter_recurse(&it, &variant);
        if (dbus_message_iter_get_arg_type(&variant) == DBUS_TYPE_UINT32) {
            dbus_uint32_t v = 0;
            dbus_message_iter_get_basic(&variant, &v);
            dark = (v == 1);
        }
    }
    dbus_message_unref(reply);
    return dark;
}

static void appearance_init(void) {
    DBusError err;
    dbus_error_init(&err);
    g_dbus = dbus_bus_get(DBUS_BUS_SESSION, &err);
    if (g_dbus == NULL) {
        dbus_error_free(&err);
        return;
    }
    // Live updates: watch the portal's SettingChanged. The connection's fd
    // joins the poll set so a theme switch repaints without a ticker.
    dbus_bus_add_match(g_dbus,
                       "type='signal',interface='org.freedesktop.portal.Settings',"
                       "member='SettingChanged'",
                       NULL);
    dbus_connection_flush(g_dbus);
}

static void report_appearance(void) {
    g.config.on_appearance(g.config.ctx, portal_prefers_dark() ? 1 : 0);
}

// Drains pending D-Bus signals; re-reports appearance if one was a
// SettingChanged. Called when the connection fd polls readable.
static void appearance_pump(void) {
    if (g_dbus == NULL) return;
    dbus_connection_read_write(g_dbus, 0);
    DBusMessage *msg;
    int changed = 0;
    while ((msg = dbus_connection_pop_message(g_dbus)) != NULL) {
        if (dbus_message_is_signal(msg, "org.freedesktop.portal.Settings",
                                   "SettingChanged"))
            changed = 1;
        dbus_message_unref(msg);
    }
    if (changed) {
        report_appearance();
        maybe_repaint();
    }
}
#else
static void appearance_init(void) {}
static void report_appearance(void) { g.config.on_appearance(g.config.ctx, 0); }
static void appearance_pump(void) {}
#endif

// ---- run ----

int32_t nokre_shell_run(const nokre_shell_config *config) {
    g.config = *config;
    g.scale = 1;
    // A paste consumer can close the selection pipe mid-write (ds_send);
    // ignore SIGPIPE so that surfaces as EPIPE, never a process kill.
    signal(SIGPIPE, SIG_IGN);
    g.repeat_fd = -1;
    g.wake_fd = -1;
    g.single_fd = -1;
    pthread_mutex_init(&g.post_lock, NULL);

    // Deep-link: pull argv from /proc/self/cmdline (Zig's run() carries no
    // argv). Each argument is NUL-separated there.
    char *launch = NULL;
    size_t launch_len = 0;
    {
        int fd = open("/proc/self/cmdline", O_RDONLY | O_CLOEXEC);
        if (fd >= 0) {
            static char cmd[8192];
            ssize_t total = read(fd, cmd, sizeof(cmd) - 1);
            close(fd);
            if (total > 0) {
                cmd[total] = 0;
                // Walk NUL-separated args; the first with "://" is the URL.
                size_t off = 0;
                int argi = 0;
                while (off < (size_t)total) {
                    const char *arg = cmd + off;
                    size_t alen = strlen(arg);
                    if (argi > 0 && strstr(arg, "://") != NULL) {
                        launch = malloc(alen ? alen : 1);
                        if (launch != NULL) {
                            memcpy(launch, arg, alen);
                            launch_len = alen;
                        }
                        break;
                    }
                    off += alen + 1;
                    argi++;
                }
            }
        }
    }

    // Single-instance: bind (primary) or forward the URL and exit.
    int forwarded = 0;
    g.single_fd = single_instance_bind(config->title, launch, launch_len, &forwarded);
    if (forwarded) {
        free(launch);
        return 0; // handed the URL to the running instance
    }
    if (launch != NULL) {
        nokre_deep_link_dispatch(launch, launch_len); // buffered until install
        free(launch);
    }

    g.display = wl_display_connect(NULL);
    if (g.display == NULL) return 1;
    g.registry = wl_display_get_registry(g.display);
    wl_registry_add_listener(g.registry, &registry_listener, NULL);
    wl_display_roundtrip(g.display); // globals in
    if (g.compositor == NULL || g.shm == NULL || g.wm_base == NULL) return 1;

    g.xkb_ctx = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    g.repeat_fd = timerfd_create(CLOCK_MONOTONIC, TFD_CLOEXEC | TFD_NONBLOCK);
    g.wake_fd = eventfd(0, EFD_CLOEXEC | EFD_NONBLOCK);

    g.logical_w = config->logical_w;
    g.logical_h = config->logical_h;

    g.surface = wl_compositor_create_surface(g.compositor);
    wl_surface_add_listener(g.surface, &surface_listener, NULL);
    g.xdg_surface = xdg_wm_base_get_xdg_surface(g.wm_base, g.surface);
    xdg_surface_add_listener(g.xdg_surface, &xdg_surface_listener, NULL);
    g.toplevel = xdg_surface_get_toplevel(g.xdg_surface);
    xdg_toplevel_add_listener(g.toplevel, &toplevel_listener, NULL);
    xdg_toplevel_set_title(g.toplevel, config->title);
    xdg_toplevel_set_app_id(g.toplevel, config->title);

    // Clipboard + IME objects, once the seat exists.
    if (g.ddm != NULL && g.seat != NULL) {
        g.data_device = wl_data_device_manager_get_data_device(g.ddm, g.seat);
        wl_data_device_add_listener(g.data_device, &data_device_listener, NULL);
    }
    if (g.ti_manager != NULL && g.seat != NULL) {
        g.text_input = zwp_text_input_manager_v3_get_text_input(g.ti_manager, g.seat);
        zwp_text_input_v3_add_listener(g.text_input, &text_input_listener, NULL);
    }

    wl_surface_commit(g.surface); // ask for the first configure
    appearance_init();

    // on_ready before the first frame (the a11y adapter attaches here);
    // publish the surface as the wake target and report appearance.
    config->on_ready(config->ctx, g.surface, "NokreWindow");
    report_appearance();

    // The event loop: block in poll() at rest, wake on the display, the
    // wake eventfd, keyboard repeat, the single-instance socket, or D-Bus.
    while (!g.closed) {
        // Prepare-read handshake so we never sleep with unread events.
        while (wl_display_prepare_read(g.display) != 0)
            wl_display_dispatch_pending(g.display);
        wl_display_flush(g.display);

        struct pollfd fds[5];
        int nfds = 0;
        int i_display = nfds;
        fds[nfds].fd = wl_display_get_fd(g.display);
        fds[nfds].events = POLLIN;
        nfds++;
        int i_wake = nfds;
        fds[nfds].fd = g.wake_fd;
        fds[nfds].events = POLLIN;
        nfds++;
        int i_repeat = nfds;
        fds[nfds].fd = g.repeat_fd;
        fds[nfds].events = POLLIN;
        nfds++;
        int i_single = -1;
        if (g.single_fd >= 0) {
            i_single = nfds;
            fds[nfds].fd = g.single_fd;
            fds[nfds].events = POLLIN;
            nfds++;
        }
#ifdef NOKRE_HAVE_DBUS
        int i_dbus = -1;
        int dbus_fd = -1;
        if (g_dbus != NULL &&
            dbus_connection_get_unix_fd(g_dbus, &dbus_fd) && dbus_fd >= 0) {
            i_dbus = nfds;
            fds[nfds].fd = dbus_fd;
            fds[nfds].events = POLLIN;
            nfds++;
        }
#endif
        int rc = poll(fds, (nfds_t)nfds, -1);
        if (rc < 0) {
            // poll left revents untouched on error; never read them. EINTR
            // (a delivered signal) just restarts the handshake; anything
            // else is fatal. cancel_read matches the prepare_read above.
            wl_display_cancel_read(g.display);
            if (errno == EINTR) continue;
            break;
        }

        if (fds[i_display].revents & POLLIN) wl_display_read_events(g.display);
        else wl_display_cancel_read(g.display);
        wl_display_dispatch_pending(g.display);

        if (fds[i_wake].revents & POLLIN) {
            uint64_t drained;
            while (read(g.wake_fd, &drained, sizeof(drained)) == sizeof(drained)) {}
            drain_posts();
        }
        if (fds[i_repeat].revents & POLLIN) {
            uint64_t ticks;
            if (read(g.repeat_fd, &ticks, sizeof(ticks)) == sizeof(ticks) &&
                g.repeat_key != 0)
                dispatch_key(g.repeat_key);
        }
        if (i_single >= 0 && (fds[i_single].revents & POLLIN)) single_instance_accept();
#ifdef NOKRE_HAVE_DBUS
        if (i_dbus >= 0 && (fds[i_dbus].revents & POLLIN)) appearance_pump();
#endif

        // Every batch may have changed what the focused element wants and
        // whether the frame is dirty; reconcile both after dispatch.
        sync_text_input();
        if (g.dirty) paint();
    }

    // Teardown: destroy in creation-reverse; the app's own deinit (Zig
    // side) joins workers before this returns.
    disarm_repeat();
    if (g.clip_source) wl_data_source_destroy(g.clip_source);
    free(g.clip_text);
    for (int b = 0; b < 2; b++) {
        if (g.bufs[b].buffer) {
            wl_buffer_destroy(g.bufs[b].buffer);
            munmap(g.bufs[b].data, g.bufs[b].cap);
        }
    }
    if (g.xkb_state) xkb_state_unref(g.xkb_state);
    if (g.xkb_keymap) xkb_keymap_unref(g.xkb_keymap);
    if (g.xkb_ctx) xkb_context_unref(g.xkb_ctx);
    // Reset the fds to -1 as they close: the a11y adapter is detached by
    // linux.zig only after this returns, so a late off-thread action could
    // still call nokre_shell_post_main — the -1 makes its wake_fd guard fail
    // (a dropped post during shutdown), never a write to a recycled fd.
    if (g.repeat_fd >= 0) {
        close(g.repeat_fd);
        g.repeat_fd = -1;
    }
    pthread_mutex_lock(&g.post_lock);
    int wf = g.wake_fd;
    g.wake_fd = -1;
    // Free any posts that never ran (process is exiting; do not run app code).
    for (struct nokre_post_item *it = g.post_head; it != NULL;) {
        struct nokre_post_item *next = it->next;
        free(it);
        it = next;
    }
    g.post_head = g.post_tail = NULL;
    pthread_mutex_unlock(&g.post_lock);
    if (wf >= 0) close(wf);
    if (g.single_fd >= 0) {
        close(g.single_fd);
        g.single_fd = -1;
    }
    wl_display_disconnect(g.display);
    return 0;
}
